---
exclude_paths:
  - '**/Examples/**'
  - '**/UnitTests/**'
  - '**/Editor/**'
  - '**/PlayModeTests/**' 
  - '**/netstandard2.0/**'
  - '**/Plugins/**'
  - '**/Scripts/PubnubExample.*'
  - '**/PubnubApi.Snippets/**'
  