name: c-sharp
version: "4.3.0.0"
schema: 1
scm: github.com/pubnub/c-sharp
changelog: 
  - version: 4.3.0.0
    date: December 12, 2019
    changes:
      - type: Improvement
        text: Added APNS2 support for mobile push.
      - type: Improvement
        text: Added helper class to build mobile push payload.
      - type: Improvement
        text: Refactored code for PAM Signature.
  - version: 4.2.0.0
    date: October 15, 2019
    changes:
      - type: Improvement
        text: Added IncludeMeta option to History.
      - type: Improvement
        text: Added new feature FetchHistory.
      - type: Improvement
        text: Added support for Message Actions.
      - type: Improvement
        text: Fix for ManageMembers and ManageMemberships when multiple include fields are provided.
  - version: 4.1.0.0
    date: September 26, 2019
    changes:
      - type: Improvement
        text: Fix for MessageCounts when multiple channels are used.
      - type: Improvement
        text: Fix for PAM Signature when case-sensitive param keys are provided.
      - type: Improvement
        text: Refactored all calls that use PAM signature to use  v2 format signature.
      - type: Improvement
        text: Implemented PAMv3 to all Objects.
      - type: Improvement
        text: New feature Token Management System to all Objects.
  - version: 4.0.33.0
    date: August 22, 2019
    changes:
      - type: Improvement
        text: Modified Signal listener message type to PNSignalResult.
      - type: Improvement
        text: Added ObjectsAPI feature.
  - version: 4.0.32.0
    date: August 08, 2019
    changes:
      - type: Improvement
        text: Async() is deprecated. Use Execute() instead.
      - type: Improvement
        text: Added Signal feature.
  - version: 4.0.31.0
    date: July 25, 2019
    changes:
      - type: Improvement
        text: Refactored code to encode unsafe chars ignored by EscapeDataString in NET35/NET40
  - version: 4.0.30.0
    date: May 28, 2019
    changes:
      - type: Improvement
        text: Refactored code to enforce minimum PresenceTimeout value to 20
      - type: Improvement
        text: Refactored code to handle bool type in presence state
  - version: 4.0.29.0
    date: Apr 25, 2019
    changes:
      - type: Improvement
        text: Fix to retrieve channel name for PNPresenceEventResult when channel group is used
  - version: 4.0.28.0
    date: Mar 28, 2019
    changes:
      - type: Improvement
        text: Fix for MessageCounts feature when multiple channels or timetokens are used with PAM enabled keys
  - version: 4.0.27.0
    date: Mar 13, 2019
    changes:
      - type: Improvement
        text: Added MessageCounts feature to get count of messages published since a given time
  - version: 4.0.26.0
    date: Feb 14, 2019
    changes:
      - type: Improvement
        text: Fix to capture last timetoken when subscribe request timeout/terminated
  - version: 4.0.25.0
    date: Feb 07, 2019
    changes:
      - type: Improvement
        text: Refactored code to allow tilde char for publish GET with secret key
      - type: Improvement
        text: Minor code refactoring based on Codacy analysis
  - version: 4.0.24.0
    date: Oct 11, 2018
    changes:
      - type: Improvement
        text: Code refactor to check null value of variables related to Reconnect usage
  - version: 4.0.23.0
    date: Oct 01, 2018
    changes:
      - type: Improvement
        text: Code refactor based on codacy rules on unused code
      - type: Improvement
        text: Refactored code to handle WebException from HttpRequestException for NetStandard platforms
  - version: 4.0.22.0
    date: Sept 06, 2018
    changes:
      - type: Improvement
        text: Added Grant delete permission feature
      - type: Improvement
        text: Modified SDK dependency Portable.BouncyCastle minimum version to 1.8.1.2
  - version: 4.0.21.0
    date: Aug 13, 2018
    changes:
      - type: Improvement
        text: Refactored code for performance improvement
      - type: Improvement
        text: Refactored CleanupTelemetryData
  - version: 4.0.20.0
    date: Aug 06, 2018
    changes:
      - type: Improvement
        text: Refactored code to publish multiple emoji characters
      - type: Improvement
        text: Refactored code to improve performance of Publish/Fire/Grant/Subscribe/Unsubscribe requests targeting .net framework
  - version: 4.0.19.0
    date: Jul 12, 2018
    changes:
      - type: Improvement
        text: Code refactor to maintain separate instance id during multi-instancing
  - version: 4.0.18.0
    date: Jun 20, 2018
    changes:
      - type: Improvement
        text: Added Publisher property to PNMessageResult of subscribe
      - type: Improvement
        text: Added PNException class and refactored code internally around status response
  - version: 4.0.17.0
    date: May 30, 2018
    changes:
      - type: Improvement
        text: Code refactor related to MultiplexExceptionHandler
      - type: Improvement
        text: Support to Apple Watch
      - type: Improvement
        text: Code refactor related to PubnubInstance
  - version: 4.0.16.0
    date: Apr 09, 2018
    changes:
      - type: Improvement
        text: Code refactor to ClientNetworkStatus
      - type: Improvement
        text: Proxy support for HttpClient
      - type: Improvement
        text: Code refactor to Telemetry
      - type: Improvement
        text: Reduced internal subscribe heartbeat interval for improvement in message delivery
  - version: 4.0.15.0
    date: Mar 22, 2018
    changes:
      - type: Improvement
        text: Feature to add external query params
      - type: Improvement
        text: Internal deduping mechanism when devices cross regions (DedupOnSubscribe)
      - type: Improvement
        text: Added provision to SupressLeaveEvents
      - type: Improvement
        text: Refactored code related to network check time request for non-200 response logging
  - version: 4.0.14.0
    date: Feb 15, 2018
    changes:
      - type: Improvement
        text: Fix for Publish Sync 
      - type: Improvement
        text: Refactored Int32/Int64 Parse to TryParse
      - type: Improvement
        text: Code refactor based on Codacy
  - version: 4.0.13.0
    date: Jan 18, 2018
    changes:
      - type: Improvement
        text: Relay server sent error status to PNStatus for Publish request 
      - type: Improvement
        text: Refactored to allow colon char for publish with secret key
  - version: 4.0.12.0
    date: Dec 21, 17
    changes:
      - type: Improvement
        text: Relay server sent 403 status to PNStatus for PCL 
      - type: Improvement
        text: Resolved array type published message for Subscribe&lt;string&gt;
  - version: 4.0.11.0
    date: Dec 14, 17
    changes:
      - type: Improvement
        text: Refactored by applying JArray.Parse for history and time json response
  - version: 4.0.10.0
    date: Dec 13, 17
    changes:
      - type: Improvement
        text: Refactored code by replacing Add with AddOrGet for ConcurrentDictionary
      - type: Improvement
        text: Added exception handling in TerminateReconnectTimer
      - type: Improvement
        text: Code refactor based on Codacy recommendation
  - version: 4.0.9.0
    date: Dec 05, 17
    changes:
      - type: Improvement
        text: Return PNStatus for non-subscribe requests timeout
      - type: Improvement
        text: Fix for PAM Grant requests to work independent of device locale
      - type: Improvement
        text: Code refactor based on Codacy recommendation
  - version: 4.0.8.0
    date: Nov 09, 17
    changes:
      - type: Improvement
        text: Added bool return value for AddListener and RemoveListener
      - type: Improvement
        text: ResetTimeToken option for Reconnect and bool return for Reconnect/Disconnect
      - type: Improvement
        text: Resubscribe fix when channelgroup is used
  - version: 4.0.7.0
    date: Nov 01, 17
    changes:
      - type: Improvement
        text: Added exception handling to AddListener and RemoveListener
      - type: Improvement
        text: Code refactor to address collection modified error in TelemetryManager
      - type: Improvement
        text: Code refactor based on Codacy recommendation
  - version: 4.0.6.0
    date: Oct 27, 17
    changes:
      - type: Improvement
        text: Added null check in exception catch block during network reconnect
      - type: Improvement
        text: Refactored code to send correct channel group, if exist, to PNStatus during network reconnect
      - type: Improvement
        text: Fix for delete message from history
      - type: Improvement
        text: Code refactor based on Codacy recommendation
  - version: 4.0.5.2
    date: Oct 10, 17
    changes:
      - type: Improvement
        text: Added exception handling for subscribe and unsubscribe internal exceptions
  - version: 4.0.5.1
    date: Sept 26, 17
    changes:
      - type: Improvement
        text: Added new method RemoveAllPushNotificationsFromDeviceWithPushToken
      - type: Improvement
        text: Code refactor on Reconnect
      - type: Improvement
        text: Code refactor based on Codacy recommendation
  - version: 4.0.4.1
    date: Sept 19, 17
    changes:
      - type: Improvement
        text: Added Telemetry feature
      - type: Improvement
        text: Fix for PNPushListProvisionsResult
  - version: 4.0.3.2
    date: Sept 06, 17
    changes:
      - type: Improvement
        text: Added HereNowRefresh to PNPresenceEventResult
      - type: Improvement
        text: PCL version duplicate message fix for multiple disconnet/reconnect
  - version: 4.0.3.1
    date: Aug 18, 17
    changes:
      - type: Improvement
        text: Refactored code to handle exception in Unsubscribe and query builder functionality
      - type: Improvement
        text: Migrated source code from VS 2015 to VS 2017
      - type: Improvement
        text: Added DeleteMessages feature
  - version: 4.0.2.2
    date: Jul 20, 17
    changes:
      - type: Improvement
        text: Code refactor to fix subscribe timeout and reconnect
  - version: 4.0.2.0
    date: Jul 05, 17
    changes:
      - type: Improvement
        text: Refactored code for application level grant
      - type: Improvement
        text: Refactored code to reuse HttpClient instance
      - type: Improvement
        text: Refactored code to handle Pubnub multi-instancing
  - version: 4.0.1.7
    date: Jun 07, 17
    changes:
      - type: Improvement
        text: Fix for publish with UsePOST and cipher key
      - type: Improvement
        text: Handling object array for History response
  - version: 4.0.1.6
    date: Apr 15, 17
    changes:
      - type: Improvement
        text: Fix for subscribe connect status callback
      - type: Improvement
        text: Message null value check for publish
  - version: 4.0.1.5
    date: Apr 06, 17
    changes:
      - type: Improvement
        text: Refactored to handle thread blocking
  - version: 4.0.1.4
    date: Mar 31, 17
    changes:
      - type: Improvement
        text: Fix to support Xamarin.Android Pubnub SDK install using Visual Studio
  - version: 4.0.1.3
    date: Mar 29, 17
    changes:
      - type: Improvement
        text: Added code to handle presence interval event
      - type: Improvement
        text: Code refactor per CA2000 code analysis
  - version: 4.0.1.3-rc13
    changes:
      - type: Improvement
        text: Refactored to address false alert log and timeout messages.
  - version: 4.0.1.3-rc12
    changes:
      - type: Improvement
        text: Support for ASP.NET/MVC project template projects.
  - version: 4.0.1.3-rc11
    changes:
      - type: Improvement
        text: Replaced HttpClient with compatible lib for .net 4.5/4.61 to support VS 2013.
  - version: 4.0.1.3-rc10
    changes:
      - type: bug fix
        text: Comma encoding fix for multi channelgroups
      - type: bug fix
        text: Fixed channel remove from channelgroup
  - version: 4.0.1.3-rc9
    changes:
      - type: bug fix
        text: Message fix for history when timetoken=false.
  - version: 4.0.1.3-rc8
    changes:
      - type: improvement
        text: Added pn- prefix to default uuid.
  - version: 4.0.1.3-rc7
    changes:
      - type: bug fix
        text: pcl profile 111 subscribe message fix.
  - version: 4.0.1.3-rc6
    changes:
      - type: bug fix
        text: Timetoken fix for subscribed messages.
  - version: 4.0.1.3-rc5
    changes:
      - type: improvement and bug fix
        text: HttpClient to supported platforms. Fixed Unsubscribe issue.
  - version: 4.0.1.3-rc1
    changes:
      - type: improvement
        text: Derived classes for inline coding.
  - version: 4.0.1.2-rc1
    changes:
      - type: improvement
        text: Cipher typo, Origin change.
  - version: 4.0.1.0-rc1
    changes:
      - type: improvement
        text: initial v4 version.
features: 
  access:
    - ACCESS-GRANT
    - ACCESS-GRANT-MANAGE
    - ACCESS-GRANT-DELETE
    - ACCESS-GRANT-V3
    - ACCESS-TOKEN-MANAGEMENT
    - ACCESS-SECRET-KEY-ALL-ACCESS    
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  notify:
    - REQUEST-MESSAGE-COUNT-EXCEEDED
  push:
    - PUSH-ADD-DEVICE-TO-CHANNELS
    - PUSH-REMOVE-DEVICE-FROM-CHANNELS
    - PUSH-LIST-CHANNELS-FROM-DEVICE
    - PUSH-REMOVE-DEVICE
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
    - PRESENCE-HEARTBEAT
  publish:
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-POST
    - PUBLISH-ASYNC
    - PUBLISH-FIRE 
    - PUBLISH-REPLICATION-FLAG
    - PUBLISH-MESSAGE-TTL
  storage:
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
    - STORAGE-DELETE-MESSAGES
    - STORAGE-FETCH-MESSAGES
    - STORAGE-MESSAGE-COUNT
    - STORAGE-HISTORY-WITH-META
    - STORAGE-FETCH-WITH-META
    - STORAGE-FETCH-WITH-MESSAGE-ACTIONS
  time:
    - TIME-TIME
  subscribe:
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-FILTER-EXPRESSION
    - SUBSCRIBE-PUBLISHER-UUID
    - SUBSCRIBE-SIGNAL-LISTENER
    - SUBSCRIBE-OBJECTS-LISTENER
  signal:
    - SIGNAL-SEND
  objects:
    - OBJECTS-GET-USERS
    - OBJECTS-GET-USER
    - OBJECTS-CREATE-USER
    - OBJECTS-UPDATE-USER
    - OBJECTS-DELETE-USER
    - OBJECTS-GET-SPACES
    - OBJECTS-CREATE-SPACE
    - OBJECTS-GET-SPACE
    - OBJECTS-UPDATE-SPACE
    - OBJECTS-DELETE-SPACE
    - OBJECTS-GET-MEMBERSHIPS
    - OBJECTS-MANAGE-MEMBERSHIPS
    - OBJECTS-GET-MEMBERS
    - OBJECTS-MANAGE-MEMBERS
  message-actions:
    - MESSAGE-ACTIONS-GET
    - MESSAGE-ACTIONS-ADD
    - MESSAGE-ACTIONS-REMOVE    
  others:
    - TELEMETRY
    - QUERY-PARAM    
supported-platforms:
  - 
    version: Pubnub 'C#' 4.3.0.0
    platforms:
      - Windows 10 and up
      - Windows Server 2008 and up
    frameworks:
      - .Net Framework 3.5
      - .Net Framework 4.0
      - .Net Framework 4.5
      - .Net Framework 4.6.1+
  - 
    version: PubnubPCL 'C#' 4.3.0.0
    platforms:
      - Xamarin.Android
      - Xamarin.iOS
      - Xamarin.Mac
      - Xamarin.Forms
      - Windows 10
      - Mac OS X 10 and up
      - Windows Server 2008 and up
    frameworks:      
      - Mono 4.8.0
      - .Net Standard 1.0
      - .Net Standard 1.1
      - .Net Standard 1.3
      - .Net Standard 1.4
      - .Net Standard 2.0
      - .Net Core
  - 
    version: PubnubUWP 'C#' 4.3.0.0
    platforms:
      - Windows Phone 10
      - Universal Windows Apps
      - Windows 10
