
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label lblHead;
	private global::Gtk.Button btnSettings;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textViewOutput;
	private global::Gtk.Button btnUnsub;
	private global::Gtk.Button btnTime;
	private global::Gtk.Button btnHereNow;
	private global::Gtk.Button btnDetailedHistory;
	private global::Gtk.Button btnPresence;
	private global::Gtk.Button btnUnsubPres;
	private global::Gtk.Button btnPublish;
	private global::Gtk.Button btnSubscribe;
	private global::Gtk.Button btnCancel;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Gravity = ((global::Gdk.Gravity)(5));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblHead = new global::Gtk.Label ();
		this.lblHead.WidthRequest = 400;
		this.lblHead.Name = "lblHead";
		this.fixed1.Add (this.lblHead);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblHead]));
		w1.X = 246;
		w1.Y = 23;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnSettings = new global::Gtk.Button ();
		this.btnSettings.WidthRequest = 180;
		this.btnSettings.CanFocus = true;
		this.btnSettings.Name = "btnSettings";
		this.btnSettings.UseUnderline = true;
		this.btnSettings.Label = global::Mono.Unix.Catalog.GetString ("Settings");
		this.fixed1.Add (this.btnSettings);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnSettings]));
		w2.X = 27;
		w2.Y = 19;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		this.fixed1.Add (this.GtkScrolledWindow1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow1]));
		w3.X = 82;
		w3.Y = 357;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textViewOutput = new global::Gtk.TextView ();
		this.textViewOutput.WidthRequest = 549;
		this.textViewOutput.HeightRequest = 350;
		this.textViewOutput.CanFocus = true;
		this.textViewOutput.Name = "textViewOutput";
		this.textViewOutput.Editable = false;
		this.GtkScrolledWindow.Add (this.textViewOutput);
		this.fixed1.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
		w5.X = 229;
		w5.Y = 59;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnUnsub = new global::Gtk.Button ();
		this.btnUnsub.WidthRequest = 180;
		this.btnUnsub.CanFocus = true;
		this.btnUnsub.Name = "btnUnsub";
		this.btnUnsub.UseUnderline = true;
		this.btnUnsub.Label = global::Mono.Unix.Catalog.GetString ("Unsubscribe");
		this.fixed1.Add (this.btnUnsub);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnUnsub]));
		w6.X = 26;
		w6.Y = 295;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnTime = new global::Gtk.Button ();
		this.btnTime.WidthRequest = 180;
		this.btnTime.CanFocus = true;
		this.btnTime.Name = "btnTime";
		this.btnTime.UseUnderline = true;
		this.btnTime.Label = global::Mono.Unix.Catalog.GetString ("Time");
		this.fixed1.Add (this.btnTime);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnTime]));
		w7.X = 26;
		w7.Y = 263;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnHereNow = new global::Gtk.Button ();
		this.btnHereNow.WidthRequest = 180;
		this.btnHereNow.CanFocus = true;
		this.btnHereNow.Name = "btnHereNow";
		this.btnHereNow.UseUnderline = true;
		this.btnHereNow.Label = global::Mono.Unix.Catalog.GetString ("Here Now");
		this.fixed1.Add (this.btnHereNow);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnHereNow]));
		w8.X = 26;
		w8.Y = 230;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnDetailedHistory = new global::Gtk.Button ();
		this.btnDetailedHistory.WidthRequest = 180;
		this.btnDetailedHistory.CanFocus = true;
		this.btnDetailedHistory.Name = "btnDetailedHistory";
		this.btnDetailedHistory.UseUnderline = true;
		this.btnDetailedHistory.Label = global::Mono.Unix.Catalog.GetString ("Detailed History");
		this.fixed1.Add (this.btnDetailedHistory);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnDetailedHistory]));
		w9.X = 27;
		w9.Y = 196;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnPresence = new global::Gtk.Button ();
		this.btnPresence.WidthRequest = 180;
		this.btnPresence.CanFocus = true;
		this.btnPresence.Name = "btnPresence";
		this.btnPresence.UseUnderline = true;
		this.btnPresence.Label = global::Mono.Unix.Catalog.GetString ("Presence");
		this.fixed1.Add (this.btnPresence);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnPresence]));
		w10.X = 28;
		w10.Y = 163;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnUnsubPres = new global::Gtk.Button ();
		this.btnUnsubPres.WidthRequest = 180;
		this.btnUnsubPres.CanFocus = true;
		this.btnUnsubPres.Name = "btnUnsubPres";
		this.btnUnsubPres.UseUnderline = true;
		this.btnUnsubPres.Label = global::Mono.Unix.Catalog.GetString ("Unsubscribe Presence");
		this.fixed1.Add (this.btnUnsubPres);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnUnsubPres]));
		w11.X = 26;
		w11.Y = 328;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnPublish = new global::Gtk.Button ();
		this.btnPublish.WidthRequest = 180;
		this.btnPublish.CanFocus = true;
		this.btnPublish.Name = "btnPublish";
		this.btnPublish.UseUnderline = true;
		this.btnPublish.Label = global::Mono.Unix.Catalog.GetString ("Publish");
		this.fixed1.Add (this.btnPublish);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnPublish]));
		w12.X = 28;
		w12.Y = 130;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnSubscribe = new global::Gtk.Button ();
		this.btnSubscribe.WidthRequest = 180;
		this.btnSubscribe.CanFocus = true;
		this.btnSubscribe.Name = "btnSubscribe";
		this.btnSubscribe.UseUnderline = true;
		this.btnSubscribe.Label = global::Mono.Unix.Catalog.GetString ("Subscribe");
		this.fixed1.Add (this.btnSubscribe);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnSubscribe]));
		w13.X = 29;
		w13.Y = 97;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnCancel = new global::Gtk.Button ();
		this.btnCancel.WidthRequest = 180;
		this.btnCancel.CanFocus = true;
		this.btnCancel.Name = "btnCancel";
		this.btnCancel.UseUnderline = true;
		this.btnCancel.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
		this.fixed1.Add (this.btnCancel);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnCancel]));
		w14.X = 29;
		w14.Y = 64;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 815;
		this.DefaultHeight = 613;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnSettings.Clicked += new global::System.EventHandler (this.SettingsClicked);
		this.btnUnsub.Clicked += new global::System.EventHandler (this.UnsubscribeClicked);
		this.btnTime.Clicked += new global::System.EventHandler (this.TimeClicked);
		this.btnHereNow.Clicked += new global::System.EventHandler (this.HereNowClicked);
		this.btnDetailedHistory.Clicked += new global::System.EventHandler (this.DetailedHistoryClicked);
		this.btnPresence.Clicked += new global::System.EventHandler (this.PresenceClicked);
		this.btnUnsubPres.Clicked += new global::System.EventHandler (this.UnsubscribePresenceClicked);
		this.btnPublish.Clicked += new global::System.EventHandler (this.PublishClicked);
		this.btnSubscribe.Clicked += new global::System.EventHandler (this.SubscribeClicked);
	}
}
