#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("PubNubMessaging.Example.Resource", IsApplication=true)]

namespace PubNubMessaging.Example
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PubNubMessaging.Resource.String.library_name = global::PubNubMessaging.Example.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int customdialog = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int drawer_shadow_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int drawer_shadow_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_drawer_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_drawer_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int monoandroidsplash = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int btnCancel = 2131099654;
			
			// aapt resource value: 0x7f060025
			public const int btnDetailedHis = 2131099685;
			
			// aapt resource value: 0x7f060018
			public const int btnGrant = 2131099672;
			
			// aapt resource value: 0x7f060026
			public const int btnHereNow = 2131099686;
			
			// aapt resource value: 0x7f060021
			public const int btnLaunch = 2131099681;
			
			// aapt resource value: 0x7f060024
			public const int btnPresence = 2131099684;
			
			// aapt resource value: 0x7f060020
			public const int btnProxy = 2131099680;
			
			// aapt resource value: 0x7f060036
			public const int btnProxyCancel = 2131099702;
			
			// aapt resource value: 0x7f060035
			public const int btnProxySave = 2131099701;
			
			// aapt resource value: 0x7f060023
			public const int btnPublish = 2131099683;
			
			// aapt resource value: 0x7f060005
			public const int btnSet = 2131099653;
			
			// aapt resource value: 0x7f06000e
			public const int btnSet2 = 2131099662;
			
			// aapt resource value: 0x7f060022
			public const int btnSubscribe = 2131099682;
			
			// aapt resource value: 0x7f060027
			public const int btnTime = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int btnUnsub = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int btnUnsubPres = 2131099689;
			
			// aapt resource value: 0x7f06002c
			public const int drawer_layout = 2131099692;
			
			// aapt resource value: 0x7f060009
			public const int lblCGinput = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int lblChannel = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int lblChannelGroup = 2131099649;
			
			// aapt resource value: 0x7f060012
			public const int lblGrant1 = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int lblGrant2 = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int lblGrant3 = 2131099670;
			
			// aapt resource value: 0x7f060010
			public const int lblGrantChannel = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int lblGrantChannelGroup = 2131099665;
			
			// aapt resource value: 0x7f060008
			public const int lblinput0 = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int lblinput1 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int lblinput2 = 2131099660;
			
			// aapt resource value: 0x7f06002f
			public const int left_drawer = 2131099695;
			
			// aapt resource value: 0x7f06002e
			public const int newChannelGroups = 2131099694;
			
			// aapt resource value: 0x7f06002d
			public const int newChannels = 2131099693;
			
			// aapt resource value: 0x7f060034
			public const int proxyPassword = 2131099700;
			
			// aapt resource value: 0x7f060032
			public const int proxyPort = 2131099698;
			
			// aapt resource value: 0x7f060031
			public const int proxyServer = 2131099697;
			
			// aapt resource value: 0x7f060033
			public const int proxyUsername = 2131099699;
			
			// aapt resource value: 0x7f06002a
			public const int scroll = 2131099690;
			
			// aapt resource value: 0x7f060030
			public const int tbProxy = 2131099696;
			
			// aapt resource value: 0x7f060013
			public const int tbRead = 2131099667;
			
			// aapt resource value: 0x7f06001c
			public const int tbSsl = 2131099676;
			
			// aapt resource value: 0x7f060015
			public const int tbWrite = 2131099669;
			
			// aapt resource value: 0x7f060000
			public const int tvAddRemoveCgLabel = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int tvAuthLabel = 2131099655;
			
			// aapt resource value: 0x7f06000f
			public const int tvGrantLabel = 2131099663;
			
			// aapt resource value: 0x7f06001f
			public const int tvProxy = 2131099679;
			
			// aapt resource value: 0x7f060004
			public const int txtChannel = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int txtChannelGroup = 2131099650;
			
			// aapt resource value: 0x7f06001d
			public const int txtCipher = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int txtCustomUuid = 2131099678;
			
			// aapt resource value: 0x7f06001a
			public const int txtPubKey = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int txtSecKey = 2131099675;
			
			// aapt resource value: 0x7f060019
			public const int txtSubKey = 2131099673;
			
			// aapt resource value: 0x7f06002b
			public const int txtViewLog = 2131099691;
			
			// aapt resource value: 0x7f06000b
			public const int txtauth = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int txtinput2 = 2131099661;
			
			// aapt resource value: 0x7f060017
			public const int txtttl = 2131099671;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddRemoveFromChannelGroup = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AuthKey = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GrantDialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ItemMenu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Launch = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PageHomeView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Proxy = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040044
			public const int addUserState = 2130968644;
			
			// aapt resource value: 0x7f040023
			public const int app_name = 2130968611;
			
			// aapt resource value: 0x7f040034
			public const int audit = 2130968628;
			
			// aapt resource value: 0x7f040036
			public const int auditpresence = 2130968630;
			
			// aapt resource value: 0x7f040039
			public const int auth = 2130968633;
			
			// aapt resource value: 0x7f040031
			public const int authkey = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int authkeyopt = 2130968626;
			
			// aapt resource value: 0x7f04003a
			public const int authopt = 2130968634;
			
			// aapt resource value: 0x7f040056
			public const int btnChangeUuid = 2130968662;
			
			// aapt resource value: 0x7f040048
			public const int btnDelUserStateAndExit = 2130968648;
			
			// aapt resource value: 0x7f040049
			public const int btnDelUserStateAndMore = 2130968649;
			
			// aapt resource value: 0x7f04004a
			public const int btnGetUserState = 2130968650;
			
			// aapt resource value: 0x7f04004f
			public const int btnGlobalHereNow = 2130968655;
			
			// aapt resource value: 0x7f040046
			public const int btnSaveUserStateAndAddMore = 2130968646;
			
			// aapt resource value: 0x7f040045
			public const int btnSaveUserStateAndExit = 2130968645;
			
			// aapt resource value: 0x7f04004c
			public const int btnSetUserState = 2130968652;
			
			// aapt resource value: 0x7f04004b
			public const int btnUserStateInst = 2130968651;
			
			// aapt resource value: 0x7f04003f
			public const int btnWhereNow = 2130968639;
			
			// aapt resource value: 0x7f040038
			public const int btncancel = 2130968632;
			
			// aapt resource value: 0x7f040033
			public const int btngrant = 2130968627;
			
			// aapt resource value: 0x7f04003b
			public const int btnset = 2130968635;
			
			// aapt resource value: 0x7f040010
			public const int cancel = 2130968592;
			
			// aapt resource value: 0x7f04001c
			public const int channel = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int channelGroup = 2130968605;
			
			// aapt resource value: 0x7f04003c
			public const int channelgroup = 2130968636;
			
			// aapt resource value: 0x7f040028
			public const int channelinfo = 2130968616;
			
			// aapt resource value: 0x7f040021
			public const int cipher = 2130968609;
			
			// aapt resource value: 0x7f040001
			public const int customUuid = 2130968577;
			
			// aapt resource value: 0x7f040047
			public const int deleteUserState = 2130968647;
			
			// aapt resource value: 0x7f040018
			public const int detailedHistory = 2130968600;
			
			// aapt resource value: 0x7f040025
			public const int drawer_close = 2130968613;
			
			// aapt resource value: 0x7f040024
			public const int drawer_open = 2130968612;
			
			// aapt resource value: 0x7f040002
			public const int enableproxy = 2130968578;
			
			// aapt resource value: 0x7f04001e
			public const int enablessl = 2130968606;
			
			// aapt resource value: 0x7f040041
			public const int enterHeartbeatInterval = 2130968641;
			
			// aapt resource value: 0x7f040040
			public const int enterHeartbeatTime = 2130968640;
			
			// aapt resource value: 0x7f040042
			public const int enterUserStateKey = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int enterUserStateValue = 2130968643;
			
			// aapt resource value: 0x7f040055
			public const int enterUuid = 2130968661;
			
			// aapt resource value: 0x7f040051
			public const int globalHereNow = 2130968657;
			
			// aapt resource value: 0x7f04002b
			public const int grant = 2130968619;
			
			// aapt resource value: 0x7f04003d
			public const int grantchannel = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int grantchannelgroup = 2130968638;
			
			// aapt resource value: 0x7f04002c
			public const int grantread = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int grantwrite = 2130968621;
			
			// aapt resource value: 0x7f040050
			public const int hereNow = 2130968656;
			
			// aapt resource value: 0x7f040017
			public const int herenow = 2130968599;
			
			// aapt resource value: 0x7f040014
			public const int inStore = 2130968596;
			
			// aapt resource value: 0x7f040022
			public const int launch = 2130968610;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040026
			public const int menu_refresh = 2130968614;
			
			// aapt resource value: 0x7f040016
			public const int message = 2130968598;
			
			// aapt resource value: 0x7f040029
			public const int newchannel = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int newchannelGroup = 2130968618;
			
			// aapt resource value: 0x7f04002f
			public const int off = 2130968623;
			
			// aapt resource value: 0x7f04002e
			public const int on = 2130968622;
			
			// aapt resource value: 0x7f04004d
			public const int optional = 2130968653;
			
			// aapt resource value: 0x7f040015
			public const int presence = 2130968597;
			
			// aapt resource value: 0x7f040003
			public const int proxy = 2130968579;
			
			// aapt resource value: 0x7f04000f
			public const int proxyCancel = 2130968591;
			
			// aapt resource value: 0x7f040009
			public const int proxyOff = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int proxyOn = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int proxyPassword = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int proxyPort = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int proxySave = 2130968590;
			
			// aapt resource value: 0x7f04000a
			public const int proxyServer = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int proxyUsername = 2130968588;
			
			// aapt resource value: 0x7f040005
			public const int pubKey = 2130968581;
			
			// aapt resource value: 0x7f040013
			public const int publish = 2130968595;
			
			// aapt resource value: 0x7f040035
			public const int revoke = 2130968629;
			
			// aapt resource value: 0x7f040037
			public const int revokepresence = 2130968631;
			
			// aapt resource value: 0x7f040006
			public const int secKey = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int setProxy = 2130968583;
			
			// aapt resource value: 0x7f040053
			public const int showUserState = 2130968659;
			
			// aapt resource value: 0x7f040052
			public const int showUuid = 2130968658;
			
			// aapt resource value: 0x7f040020
			public const int sslOff = 2130968608;
			
			// aapt resource value: 0x7f04001f
			public const int sslOn = 2130968607;
			
			// aapt resource value: 0x7f040004
			public const int subKey = 2130968580;
			
			// aapt resource value: 0x7f040027
			public const int subchannel = 2130968615;
			
			// aapt resource value: 0x7f040011
			public const int subscribe = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int subscribeConnCallback = 2130968594;
			
			// aapt resource value: 0x7f040019
			public const int time = 2130968601;
			
			// aapt resource value: 0x7f040030
			public const int ttl = 2130968624;
			
			// aapt resource value: 0x7f04001a
			public const int unsubscribe = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int unsubscribePres = 2130968603;
			
			// aapt resource value: 0x7f040054
			public const int uuid = 2130968660;
			
			// aapt resource value: 0x7f04004e
			public const int whereNow = 2130968654;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
