//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubnubApi.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PubnubApi.Tests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[{&quot;VersionID&quot;:3.4,&quot;Timetoken&quot;:&quot;13601488652764619&quot;,&quot;OperationName&quot;:&quot;Publish&quot;,&quot;Channels&quot;:[&quot;ch1&quot;],&quot;DemoMessage&quot;:{&quot;DefaultMessage&quot;:&quot;~!@#$%^&amp;*()_+ `1234567890-= qwertyuiop[]\\ {}| asdfghjkl;&apos; :\&quot; zxcvbnm,./ &lt;&gt;? &quot;},&quot;CustomMessage&quot;:{&quot;DefaultMessage&quot;:&quot;Welcome to the world of Pubnub for Publish and Subscribe. Hah!&quot;},&quot;SampleXml&quot;:[{&quot;ID&quot;:&quot;ABCD123&quot;,&quot;Name&quot;:{&quot;First&quot;:&quot;John&quot;,&quot;Middle&quot;:&quot;P.&quot;,&quot;Last&quot;:&quot;Doe&quot;},&quot;Address&quot;:{&quot;Street&quot;:&quot;123 Duck Street&quot;,&quot;City&quot;:&quot;New City&quot;,&quot;State&quot;:&quot;New York&quot;,&quot;Country&quot;:&quot;United States&quot;}},{&quot;ID&quot;:&quot;ABCD456&quot;,&quot;Na [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ComplexMessage {
            get {
                return ResourceManager.GetString("ComplexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerous questions remain about the origins of the chemical and what impact its apparent use could have on the ongoing Syrian civil war and international involvement in it.When asked if the intelligence community&apos;s conclusion pushed the situation across President Barack Obama&apos;s \&quot;red line\&quot; that could potentially trigger more U.S. involvement in the Syrian civil war, Hagel said it&apos;s too soon to say.\&quot;We need all the facts. We need all the information,\&quot; he said. \&quot;What I&apos;ve just given you is what our intell [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LargeMessage32K {
            get {
                return ResourceManager.GetString("LargeMessage32K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %22Numerous%20questions%20remain%20about%20the%20origins%20of%20the%20chemical%20and%20what%20impact%20its%20apparent%20use%20could%20have%20on%20the%20ongoing%20Syrian%20civil%20war%20and%20international%20involvement%20in%20it.When%20asked%20if%20the%20intelligence%20community%27s%20conclusion%20pushed%20the%20situation%20across%20President%20Barack%20Obama%27s%20%5C%5C%5C%22red%20line%5C%5C%5C%22%20that%20could%20potentially%20trigger%20more%20U.S.%20involvement%20in%20the%20Syrian%20civil%20war%2C%20Hag [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LargeMessage32KStatic {
            get {
                return ResourceManager.GetString("LargeMessage32KStatic", resourceCulture);
            }
        }
    }
}
