// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AcceptanceTests.Features.Event_Engine
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Event Engine")]
    [NUnit.Framework.CategoryAttribute("featureSet=eventEngine")]
    public partial class EventEngineFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "featureSet=eventEngine"};
        
#line 1 "happy-path.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/event-engine", "Event Engine", "  This is a description of the feature", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
  #line hidden
#line 6
    testRunner.Given("the demo keyset with event engine enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Successfully receive messages")]
        [NUnit.Framework.CategoryAttribute("contract=simpleSubscribe")]
        [NUnit.Framework.CategoryAttribute("beta")]
        public void SuccessfullyReceiveMessages()
        {
            string[] tagsOfScenario = new string[] {
                    "contract=simpleSubscribe",
                    "beta"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successfully receive messages", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
  this.FeatureBackground();
#line hidden
#line 10
    testRunner.When("I subscribe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
    testRunner.When("I publish a message", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 12
    testRunner.Then("I receive the message in my subscribe response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "type",
                            "name"});
                table1.AddRow(new string[] {
                            "event",
                            "SUBSCRIPTION_CHANGED"});
                table1.AddRow(new string[] {
                            "invocation",
                            "HANDSHAKE"});
                table1.AddRow(new string[] {
                            "event",
                            "HANDSHAKE_SUCCESS"});
                table1.AddRow(new string[] {
                            "invocation",
                            "CANCEL_HANDSHAKE"});
                table1.AddRow(new string[] {
                            "invocation",
                            "EMIT_STATUS"});
                table1.AddRow(new string[] {
                            "invocation",
                            "RECEIVE_EVENTS"});
                table1.AddRow(new string[] {
                            "event",
                            "RECEIVE_SUCCESS"});
                table1.AddRow(new string[] {
                            "invocation",
                            "CANCEL_RECEIVE_EVENTS"});
                table1.AddRow(new string[] {
                            "invocation",
                            "EMIT_STATUS"});
                table1.AddRow(new string[] {
                            "invocation",
                            "EMIT_EVENTS"});
#line 13
    testRunner.And("I observe the following:", ((string)(null)), table1, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Complete handshake failure")]
        [NUnit.Framework.CategoryAttribute("contract=subscribeHandshakeFailure")]
        [NUnit.Framework.CategoryAttribute("beta")]
        public void CompleteHandshakeFailure()
        {
            string[] tagsOfScenario = new string[] {
                    "contract=subscribeHandshakeFailure",
                    "beta"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Complete handshake failure", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
  this.FeatureBackground();
#line hidden
#line 28
    testRunner.Given("a linear reconnection policy with 3 retries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 29
    testRunner.When("I subscribe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 30
    testRunner.Then("I receive an error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "type",
                            "name"});
                table2.AddRow(new string[] {
                            "event",
                            "SUBSCRIPTION_CHANGED"});
                table2.AddRow(new string[] {
                            "invocation",
                            "HANDSHAKE"});
                table2.AddRow(new string[] {
                            "event",
                            "HANDSHAKE_FAILURE"});
                table2.AddRow(new string[] {
                            "invocation",
                            "CANCEL_HANDSHAKE"});
                table2.AddRow(new string[] {
                            "invocation",
                            "HANDSHAKE_RECONNECT"});
                table2.AddRow(new string[] {
                            "event",
                            "HANDSHAKE_RECONNECT_FAILURE"});
                table2.AddRow(new string[] {
                            "invocation",
                            "CANCEL_HANDSHAKE_RECONNECT"});
                table2.AddRow(new string[] {
                            "invocation",
                            "HANDSHAKE_RECONNECT"});
                table2.AddRow(new string[] {
                            "event",
                            "HANDSHAKE_RECONNECT_FAILURE"});
                table2.AddRow(new string[] {
                            "invocation",
                            "CANCEL_HANDSHAKE_RECONNECT"});
                table2.AddRow(new string[] {
                            "invocation",
                            "HANDSHAKE_RECONNECT"});
                table2.AddRow(new string[] {
                            "event",
                            "HANDSHAKE_RECONNECT_FAILURE"});
                table2.AddRow(new string[] {
                            "invocation",
                            "CANCEL_HANDSHAKE_RECONNECT"});
                table2.AddRow(new string[] {
                            "invocation",
                            "HANDSHAKE_RECONNECT"});
                table2.AddRow(new string[] {
                            "event",
                            "HANDSHAKE_RECONNECT_GIVEUP"});
                table2.AddRow(new string[] {
                            "invocation",
                            "CANCEL_HANDSHAKE_RECONNECT"});
                table2.AddRow(new string[] {
                            "invocation",
                            "EMIT_STATUS"});
#line 31
    testRunner.And("I observe the following:", ((string)(null)), table2, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Handshake failure recovery")]
        [NUnit.Framework.CategoryAttribute("contract=subscribeHandshakeRecovery")]
        [NUnit.Framework.CategoryAttribute("beta")]
        public void HandshakeFailureRecovery()
        {
            string[] tagsOfScenario = new string[] {
                    "contract=subscribeHandshakeRecovery",
                    "beta"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Handshake failure recovery", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
  this.FeatureBackground();
#line hidden
#line 53
    testRunner.Given("a linear reconnection policy with 3 retries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 54
    testRunner.When("I subscribe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 55
    testRunner.Then("I receive the message in my subscribe response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "type",
                            "name"});
                table3.AddRow(new string[] {
                            "event",
                            "SUBSCRIPTION_CHANGED"});
                table3.AddRow(new string[] {
                            "invocation",
                            "HANDSHAKE"});
                table3.AddRow(new string[] {
                            "event",
                            "HANDSHAKE_FAILURE"});
                table3.AddRow(new string[] {
                            "invocation",
                            "CANCEL_HANDSHAKE"});
                table3.AddRow(new string[] {
                            "invocation",
                            "HANDSHAKE_RECONNECT"});
                table3.AddRow(new string[] {
                            "event",
                            "HANDSHAKE_RECONNECT_FAILURE"});
                table3.AddRow(new string[] {
                            "invocation",
                            "CANCEL_HANDSHAKE_RECONNECT"});
                table3.AddRow(new string[] {
                            "invocation",
                            "HANDSHAKE_RECONNECT"});
                table3.AddRow(new string[] {
                            "event",
                            "HANDSHAKE_RECONNECT_SUCCESS"});
                table3.AddRow(new string[] {
                            "invocation",
                            "CANCEL_HANDSHAKE_RECONNECT"});
                table3.AddRow(new string[] {
                            "invocation",
                            "EMIT_STATUS"});
                table3.AddRow(new string[] {
                            "invocation",
                            "RECEIVE_EVENTS"});
                table3.AddRow(new string[] {
                            "event",
                            "RECEIVE_SUCCESS"});
                table3.AddRow(new string[] {
                            "invocation",
                            "CANCEL_RECEIVE_EVENTS"});
                table3.AddRow(new string[] {
                            "invocation",
                            "EMIT_STATUS"});
                table3.AddRow(new string[] {
                            "invocation",
                            "EMIT_EVENTS"});
#line 56
    testRunner.And("I observe the following:", ((string)(null)), table3, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Receiving failure recovery")]
        [NUnit.Framework.CategoryAttribute("contract=subscribeReceivingRecovery")]
        [NUnit.Framework.CategoryAttribute("beta")]
        public void ReceivingFailureRecovery()
        {
            string[] tagsOfScenario = new string[] {
                    "contract=subscribeReceivingRecovery",
                    "beta"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Receiving failure recovery", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 76
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
  this.FeatureBackground();
#line hidden
#line 77
    testRunner.When("I subscribe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 78
    testRunner.Then("I receive the message in my subscribe response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "type",
                            "name"});
                table4.AddRow(new string[] {
                            "event",
                            "SUBSCRIPTION_CHANGED"});
                table4.AddRow(new string[] {
                            "invocation",
                            "HANDSHAKE"});
                table4.AddRow(new string[] {
                            "event",
                            "HANDSHAKE_SUCCESS"});
                table4.AddRow(new string[] {
                            "invocation",
                            "CANCEL_HANDSHAKE"});
                table4.AddRow(new string[] {
                            "invocation",
                            "EMIT_STATUS"});
                table4.AddRow(new string[] {
                            "invocation",
                            "RECEIVE_EVENTS"});
                table4.AddRow(new string[] {
                            "event",
                            "RECEIVE_FAILURE"});
                table4.AddRow(new string[] {
                            "invocation",
                            "CANCEL_RECEIVE_EVENTS"});
                table4.AddRow(new string[] {
                            "invocation",
                            "RECEIVE_RECONNECT"});
                table4.AddRow(new string[] {
                            "event",
                            "RECEIVE_RECONNECT_SUCCESS"});
                table4.AddRow(new string[] {
                            "invocation",
                            "CANCEL_RECEIVE_RECONNECT"});
                table4.AddRow(new string[] {
                            "invocation",
                            "EMIT_STATUS"});
                table4.AddRow(new string[] {
                            "invocation",
                            "EMIT_EVENTS"});
                table4.AddRow(new string[] {
                            "invocation",
                            "RECEIVE_EVENTS"});
#line 79
    testRunner.And("I observe the following:", ((string)(null)), table4, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
