name: Automated product release

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  check-release:
    name: Check release required
    if: github.event.pull_request.merged && endsWith(github.repository, '-private') != true
    runs-on:
      group: Default
    outputs:
      release: ${{ steps.check.outputs.ready }}
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - id: check
        name: Check pre-release completed
        uses: ./.github/.release/actions/actions/checks/release
        with:
          token: ${{ secrets.GH_TOKEN }}
  publish-nuget:
    name: Publish to NuGet
    needs: check-release
    if: needs.check-release.outputs.release == 'true'
    runs-on:
      group: windows-gh
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # This should be the same as the one specified for on.pull_request.branches
          ref: master
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            2.1.519
            5.0.x
            6.0.x
      - name: Build packages
        env:
          WORKSPACE_PATH: ${{ github.workspace }}
        run: .\\.github\\workflows\\release\\build-packages.ps1
      - name: Publish packages
        env:
          WORKSPACE_PATH: ${{ github.workspace }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: .\\.github\\workflows\\release\\publish-packages.ps1
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: ${{ github.workspace }}\.github\.release\artifacts\*.nupkg
          retention-days: 1
  publish:
    name: Publish package
    needs: publish-nuget
    runs-on:
      group: Default
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # This should be the same as the one specified for on.pull_request.branches
          ref: master
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages
          path: ${{ github.workspace }}/.github/.release/artifacts
      - name: Create Release
        uses: ./.github/.release/actions/actions/services/github-release
        with:
          token: ${{ secrets.GH_TOKEN }}
          jira-api-key: ${{ secrets.JIRA_API_KEY }}
          last-service: true
      - name: Upload test reports
        uses: ./.github/.release/actions/actions/test-reports/upload
        with:
          token: ${{ secrets.GH_TOKEN }}
          acceptance-tests-workflow: Tests
