on: 
  workflow_dispatch:
  pull_request:
    branches: 
      - master

jobs:
  publish-nuget:
    name: Publish to NuGet
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # This should be the same as the one specified for on.pull_request.branches
          ref: master
      - name: Checkout actions
        uses: actions/checkout@v2
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Publish to NuGet
        uses: ${{ github.workspace }}.\.github\.release\actions\actions\services\nuget
        with:
          token: ${{ secrets.GH_TOKEN }}
          project-path: "${{ github.workspace }}\\src\\Api\\PubnubApi"
          package-type: API
