on: 
  workflow_dispatch:
  pull_request:
    branches: 
      - master

jobs:
  publish-nuget:
    name: Publish to NuGet
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # This should be the same as the one specified for on.pull_request.branches
          ref: master
      - name: Build packages
        run: |
          $RELEASES_PATH="${{ github.workspace }}\.github\.release"
          Get-ChildItem "${{ github.workspace }}\*" -Name -Include *.nupkg
          echo "-----> $RELEASES_PATH"
          mkdir "$RELEASES_PATH"

          cd "${{ github.workspace }}\src\Api\PubnubApi"
          dotnet pack -o "$RELEASES_PATH" -c Release
          Get-ChildItem "${{ github.workspace }}\*" -Name -Include *.nupkg

          cd "${{ github.workspace }}\src\Api\PubnubApiPCL"
          dotnet pack -o "$RELEASES_PATH" -c Release
          Get-ChildItem "${{ github.workspace }}\*" -Name -Include *.nupkg

          cd "${{ github.workspace }}\src\Api\PubnubApiUWP"
          msbuild PubnubApiUWP.csproj /t:Pack /p:Configuration=Release /p:PackageOutputPath="$RELEASES_PATH" /v:n
          Get-ChildItem "${{ github.workspace }}\*" -Name -Include *.nupkg
