on: 
  workflow_dispatch:
  pull_request:
    branches: 
      - master

jobs:
  publish-nuget:
    name: Publish to NuGet
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # This should be the same as the one specified for on.pull_request.branches
          ref: master
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Build packages
        run: |
          $RELEASES_PATH="${{ github.workspace }}\.github\.release"
          $FILES_LIST=Get-ChildItem "${{ github.workspace }}\*" -Name -Include *.nupkg
          echo "PATH -----> $RELEASES_PATH"
          echo "FILES -----> $FILES_LIST"
          mkdir "$RELEASES_PATH"

          cd "${{ github.workspace }}\src\Api\PubnubApi"
          dotnet pack -o "$RELEASES_PATH" -c Release
          $FILES_LIST=Get-ChildItem "${{ github.workspace }}\*" -Name -Include *.nupkg
          echo "FILES -----> $FILES_LIST"

          cd "${{ github.workspace }}\src\Api\PubnubApiPCL"
          dotnet pack -o "$RELEASES_PATH" -c Release
          $FILES_LIST=Get-ChildItem "${{ github.workspace }}\*" -Name -Include *.nupkg
          echo "FILES -----> $FILES_LIST"

          cd "${{ github.workspace }}\src\Api\PubnubApiUWP"
          msbuild PubnubApiUWP.csproj /t:Pack /p:Configuration=Release /p:PackageOutputPath="$RELEASES_PATH" /v:n
          $FILES_LIST=Get-ChildItem "${{ github.workspace }}\*" -Name -Include *.nupkg
          echo "FILES -----> $FILES_LIST"
