on: 
  workflow_dispatch:
  pull_request:
    branches: 
      - master

jobs:
  publish-nuget:
    name: Publish to NuGet
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # This should be the same as the one specified for on.pull_request.branches
          ref: master
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Build packages
        run: |
          $RELEASES_PATH = "${{ github.workspace }}\.github\.release"
          echo "PATH -----> $RELEASES_PATH"
          mkdir "$RELEASES_PATH"
          dir "$RELEASES_PATH"
          $VAR1 = dir -i *.nupkg
          Write-Output $VAR1

          cd "${{ github.workspace }}\src\Api\PubnubApi"
          dotnet pack -o "$RELEASES_PATH" -c Release
          dir "$RELEASES_PATH"
          $VAR2 = dir -i *.nupkg
          Write-Output $VAR2

          cd "${{ github.workspace }}\src\Api\PubnubApiPCL"
          dotnet pack -o "$RELEASES_PATH" -c Release
          dir "$RELEASES_PATH"
          $VAR3 = dir -i *.nupkg
          Write-Output $VAR3
