
namespace PubnubApi
{
    internal enum PubnubErrorCode
    {
        //www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
        None = 0,
        NameResolutionFailure = 103,
        PubnubMessageDecryptException = 104,
        WebRequestCanceled = 105,
        ConnectFailure = 106,
        PubnubObjectDisposedException = 107,
        PubnubSocketConnectException = 108,
        NoInternet = 109,
        YesInternet = 110,
        DuplicateChannel = 111,
        AlreadySubscribed = 112,
        AlreadyPresenceSubscribed = 113,
        PubnubCryptographicException = 114,
        ProtocolError = 115,
        ServerProtocolViolation = 116,
        InvalidChannel = 117,
        NotSubscribed = 118,
        NotPresenceSubscribed = 119,
        UnsubscribeFailed = 120,
        PresenceUnsubscribeFailed = 121,
        NoInternetRetryConnect = 122,
        UnsubscribedAfterMaxRetries = 123,
        PresenceUnsubscribedAfterMaxRetries = 124,
        PublishOperationTimeout = 125,
        HereNowOperationTimeout = 126,
        DetailedHistoryOperationTimeout = 127,
        TimeOperationTimeout = 128,
        PubnubInterOpSEHException = 129,
        PubnubClientMachineSleep = 130,
        SetUserStateTimeout = 131,
        GetUserStateTimeout = 132,
        WhereNowOperationTimeout = 133,
        GlobalHereNowOperationTimeout = 134,
        PAMAccessOperationTimeout = 135,
        UserStateUnchanged = 136,
        PushNotificationTimeout = 137,
        ChannelGroupTimeout = 138,
        DuplicateChannelGroup = 139,
        ReceiveFailure = 140,
        CallbackMissing = 141,

        MessageTooLarge = 4000,
        BadRequest = 4001,
        InvalidKey = 4002,
        NoUuidSpecified = 4003,
        InvalidTimestamp = 4004,
        InvalidTypeArgument = 4005,
        EmptyGroupSubscription = 4006,
        CouldNotParseRequest = 4007,
        InvalidSubscribeKey = 4010,
        PamNotEnabled = 4020,
        Forbidden = 4030,
        SignatureDoesNotMatch = 4031,
        NotFound = 4040,
        RequestUriTooLong = 4140,
        InternalServerError = 5000,
        BadGateway = 5020,
        ServiceUnavailable = 5030,
        GatewayTimeout = 5040
    }
}
